### ISSUE TITLE
Language server doesn't appear to be running for `*.bicep` files

### ISSUE THREAD

**Issue by alex-frankel** [sublimelsp/LSP-Bicep#2]
The selected language shows as "Plain Text" and "Bicep" does not show up as a language that I can select. I ran the troubleshooting tool and this was the output:

```
# Troubleshooting: Bicep
## Version
 - LSP: 1.12.1
 - Sublime Text: 4113
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "${dotnet_executable}", 
  "${storage_path}/LSP-Bicep/Bicep.LangServer.dll"
]
```
 - shell command
```sh
dotnet "C:\Users\alfran\AppData\Local\Sublime Text\Package Storage/LSP-Bicep/Bicep.LangServer.dll"
```
 - selector
```
source.bicep
```
 - priority_selector
```
source.bicep
```
 - init_options
```json
{}
```
 - settings
```json
{}
```
 - env
```json
{}
```

## Active view
 - File name
```
F:\repos\bicep-demos\app-plan-demo\stg.bicep
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": null, 
  "syntax": "Packages/Text/Plain text.tmLanguage"
}
```
 - base scope
```
text.plain
```

## Project / Workspace
 - folders
```json
[
  "F:\\repos\\bicep-demos"
]
```
 - is project: False

## LSP configuration

```json
{
  "clients": {
    "sorbet": {
      "enabled": true
    }
  }, 
  "log_debug": true, 
  "log_server": [
    "panel"
  ]
}
```
## System PATH
 - C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin
 - C:\Windows\system32
 - C:\Windows
 - C:\Windows\System32\Wbem
 - C:\Windows\System32\WindowsPowerShell\v1.0\
 - C:\Windows\System32\OpenSSH\
 - C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
 - C:\Program Files\Git\cmd
 - C:\Program Files\dotnet\
 - C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\
 - C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
 - C:\ProgramData\chocolatey\bin
 - 
 - C:\Program Files (x86)\dotnet\
 - C:\Program Files\nodejs\
 - C:\Program Files\Docker\Docker\resources\bin
 - C:\ProgramData\DockerDesktop\version-bin
 - C:\Program Files\Azure Data Studio\bin
 - C:\Program Files\PowerShell\7\
 - C:\Program Files\Microsoft VS Code\bin
 - C:\WINDOWS\system32
 - C:\WINDOWS
 - C:\WINDOWS\System32\Wbem
 - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
 - C:\WINDOWS\System32\OpenSSH\
 - C:\Users\alfran\AppData\Local\Microsoft\WindowsApps
 - C:\Users\alfran\.dotnet\tools
 - C:\Program Files (x86)\GitHub CLI\
 - C:\Users\alfran\AppData\Local\GitHubDesktop\bin
 - C:\Users\alfran\AppData\Roaming\npm
 - C:\Program Files\Azure Data Studio\bin
 - C:\Users\alfran\.rad
 - C:\Users\alfran\.azure\bin
 - C:\Users\alfran\AppData\Local\Programs\Microsoft VS Code\bin

**Comment by rwols** [comment]
The instructions in the readme state you must install this package https://packagecontrol.io/packages/Bicep

**Comment by alex-frankel** [comment]
ah that was it - thanks!!
